### ISSUE TITLE
Vulnerable for lua executors

### ISSUE THREAD

**Issue by ElPumpo** [TanguyOrtegat/esx_jb_SecurityVans#1]
https://github.com/TanguyOrtegat/esx_jb_SecurityVans/blob/b907928aa050a1e824a6ec328c2cbc37380caa75/esx_jb_SecurityVans_sv.lua#L10

**Comment by TanguyOrtegat** [comment]
i know, but each event is vulnerable for executor.... you know why if someons takes the moneycase, the one who launched the van, do recieve the item bigmoneybag?
